//
//  My-profile-FOR-YOU-screen-1MB.swift
//  MyApp
//
//  Created by Cong Le on 11/16/24.
//

///The UI elements in the image are all over place.
/// Buttons are not workings.
/// In this case, the image size is 1MB, dimention is 1284 × 2778, resolution is 72 × 72
/// Code generated by GPT-4o
import SwiftUI
struct SocialMediaCameraView: View {
    var body: some View {
        VStack(spacing: 0) {
            // Top Navigation Bar
            HStack {
                Spacer()

                Text("LIVE")
                    .underline()
                Text("Explore")
                Text("Following")
                Text("Shop")
                Text("For You")
                    .underline(true, color: .red)

                Spacer()

                Image(systemName: "magnifyingglass")
            }
            .padding(.vertical, 10)
            .background(Color.black.opacity(0.8))
            .foregroundColor(.white)

            // Spacer for Image Placeholder
            Spacer()

            // Main Image Content (Placeholder)
            VStack {
                Image("profile_picture")
                    .resizable()
                    .scaledToFill()
                    .frame(maxHeight: .infinity)
                    .clipped()
            }
            .overlay(
                VStack {
                    // Like, Comment, Share Buttons
                    Spacer()

                    VStack(spacing: 20) {
                        SideButton(icon: "heart.fill", text: "69.4K")
                        SideButton(icon: "bubble.right.fill", text: "213")
                        SideButton(icon: "arrowshape.turn.up.right.fill", text: "6,563")
                        Image("profile_thumbnail")
                            .resizable()
                            .frame(width: 50, height: 50)
                            .clipShape(Circle())
                            .overlay(
                                Circle().stroke(Color.white, lineWidth: 1.5)
                            )
                            .shadow(radius: 3)
                    }
                    .padding(.bottom, 60)

                    // Video Information
                    VStack(alignment: .leading, spacing: 5) {
                        Text("Phan Ái Vy")
                            .bold()
                        Text("Z ha #phanaizi #fyp #viral")
                        Text("See translation")
                            .font(.caption)
                            .foregroundColor(.gray)
                    }
                    .padding(.horizontal)
                    .foregroundColor(.white)
                }
            )

            // Bottom Navigation Bar
            HStack {
                TabButton(icon: "house.fill", label: "Home")
                TabButton(icon: "person.2.fill", label: "Friends", badgeValue: 1)
                TabButton(icon: "plus.circle.fill", label: "", isPlus: true)
                TabButton(icon: "tray.fill", label: "Inbox")
                TabButton(icon: "person.fill", label: "Profile")
            }
            .frame(height: 50)
            .background(Color.black.opacity(0.8))
        }
        .edgesIgnoringSafeArea(.all)
    }
}

struct SideButton: View {
    var icon: String
    var text: String

    var body: some View {
        VStack {
            Image(systemName: icon)
                .font(.title)
                .foregroundColor(.white)
            Text(text)
                .font(.footnote)
                .foregroundColor(.white)
        }
    }
}

struct TabButton: View {
    var icon: String
    var label: String
    var badgeValue: Int? = nil
    var isPlus: Bool = false

    var body: some View {
        VStack {
            ZStack {
                Image(systemName: icon)
                    .font(isPlus ? .largeTitle : .title2)
                    .foregroundColor(isPlus ? .cyan : .white)

                if let badgeValue = badgeValue, badgeValue > 0 {
                    Text("\(badgeValue)")
                        .font(.caption2)
                        .padding(4)
                        .background(Color.red)
                        .foregroundColor(.white)
                        .clipShape(Circle())
                        .offset(x: 15, y: -10)
                }
            }
            if !isPlus {
                Text(label)
                    .font(.caption)
                    .foregroundColor(.white)
            }
        }
    }
}

struct SocialMediaCameraView_Previews: PreviewProvider {
    static var previews: some View {
        SocialMediaCameraView()
    }
}
