//
//  My-profile-FOR-YOU-screen.swift
//  MyApp
//
//  Created by Cong Le on 11/16/24.
//

///The UI elements in the image are not aligned correct (but acceptable).
/// Buttons are monotone, they are clickable but not  functional with print statement.
/// In this case, the image size is 331 KB, dimention is 1284 × 2778, resolution is 72 × 72
/// Code generated by GPT-4o
import SwiftUI
struct SocialCameraInterfaceView: View {
    var body: some View {
        VStack(spacing: 0) {
            // Top Navigation Bar
            HStack(spacing: 20) {
                Image(systemName: "livephoto")
                Text("Explore")
                Text("Following")
                Text("Shop")
                Text("For You")
                    .fontWeight(.bold)
                Spacer()
                Image(systemName: "magnifyingglass")
            }
            .padding()
            .foregroundColor(.white)
            .background(Color.black.opacity(0.8))
            
            // Video Feed (Placeholder)
            ZStack(alignment: .bottomLeading) {
                Rectangle()
                    .fill(Color.gray)
                    .overlay(
                        Text("VIDEO FEED")
                            .foregroundColor(.white)
                            .font(.caption)
                    )
                
                // User Information
                VStack(alignment: .leading, spacing: 4) {
                    Text("Phan Ái Vy")
                        .fontWeight(.bold)
                        .foregroundColor(.white)
                    Text("Z ha #phanaizi #fyp #viral")
                        .foregroundColor(.white)
                    Text("See translation")
                        .font(.footnote)
                        .foregroundColor(.white)
                }
                .padding()
                
                // Like, Comment, Share, Profile Buttons
                VStack(spacing: 20) {
                    Button(action: {
                        // Like action
                    }) {
                        VStack {
                            Image(systemName: "heart.fill")
                            Text("69.4K")
                                .font(.caption)
                        }
                    }
                    .foregroundColor(.white)
                    
                    Button(action: {
                        // Comment action
                    }) {
                        VStack {
                            Image(systemName: "ellipsis.bubble.fill")
                            Text("213")
                                .font(.caption)
                        }
                    }
                    .foregroundColor(.white)

                    Button(action: {
                        // Share action
                    }) {
                        VStack {
                            Image(systemName: "arrowshape.turn.up.right.fill")
                            Text("5,094")
                                .font(.caption)
                        }
                    }
                    .foregroundColor(.white)

                    Image(systemName: "person.crop.circle.fill")
                        .resizable()
                        .frame(width: 50, height: 50)
                        .clipShape(Circle())
                        .overlay(
                            Image(systemName: "plus.circle.fill")
                                .foregroundColor(.pink)
                                .offset(x: 18, y: 18)
                        )
                }
                .padding()
                .offset(x: UIScreen.main.bounds.width / 2 - 50)
            }
            
            // Bottom Navigation Bar
            HStack {
                VStack {
                    Image(systemName: "house.fill")
                    Text("Home")
                        .font(.caption)
                }
                
                Spacer()
                
                VStack {
                    Image(systemName: "person.2.fill")
                    Text("Friends")
                        .font(.caption)
                        .overlay(
                            Circle()
                                .fill(Color.red)
                                .frame(width: 10, height: 10)
                                .offset(x: 10, y: -10),
                            alignment: .topTrailing
                        )
                }
                
                Spacer()
                
                Circle()
                    .fill(Color.white)
                    .frame(width: 50, height: 50)
                    .overlay(
                        Image(systemName: "plus")
                            .font(.title2)
                            .foregroundColor(.black)
                    )
                
                Spacer()
                
                VStack {
                    Image(systemName: "envelope.fill")
                    Text("Inbox")
                        .font(.caption)
                }
                
                Spacer()
                
                VStack {
                    Image(systemName: "person.fill")
                    Text("Profile")
                        .font(.caption)
                }
            }
            .padding()
            .foregroundColor(.gray)
            .background(Color.black)
        }
        .edgesIgnoringSafeArea(.all)
    }
}

struct SocialCameraInterfaceView_Previews: PreviewProvider {
    static var previews: some View {
        SocialCameraInterfaceView()
    }
}
