//
//  My-profile-FOR-YOU-screen_303KB.swift
//  MyApp
//
//  Created by Cong Le on 11/16/24.
//


///The UI elements in the image are all over place.
/// In this case, the image size is 303 KB, dimention is 1284 × 2778, resolution is 72 × 72
///  Buttons are not workings.
/// Code generated by GPT-4o
import SwiftUI
struct TikTokCameraInterfaceView: View {
    var body: some View {
        ZStack {
            // Background Image
            Image("exampleImage") // Replace with your image name
                .resizable()
                .scaledToFill()
                .frame(width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)
                .clipped()
                .edgesIgnoringSafeArea(.all)
            
            // Top Navigation Bar
            VStack {
                HStack {
                    Text("12:50")
                    Spacer()
                    Image(systemName: "dot.radiowaves.left.and.right")
                        .foregroundColor(.white)
                    Text("LIVE")
                    Spacer()
                    Text("Explore")
                    Spacer()
                    Text("Following")
                    Spacer()
                    Text("Shop")
                    Spacer()
                    Text("For You")
                        .underline()
                    Spacer()
                    Image(systemName: "magnifyingglass")
                }
                .foregroundColor(.white)
                .padding()
                
                Spacer()
                
                // Bottom Controls
                VStack {
                    Spacer()
                    
                    // User Interaction (Profile, Likes, Comments)
                    VStack(spacing: 20) {
                        Spacer()
                        
                        ProfileButton()
                        
                        VStack(spacing: 16) {
                            ActionButton(imageName: "heart", count: "69.4K")
                            ActionButton(imageName: "message", count: "213")
                            ActionButton(imageName: "arrowshape.turn.up.right", count: "6,563")
                        }
                    }
                    .padding(.trailing, 20)
                    
                    Spacer()
                    
                    // Video Description & Hashtags
                    HStack {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Phan Ái Vy")
                                .foregroundColor(.white)
                                .bold()
                            Text("#phanai #fyp #viral")
                                .foregroundColor(.white)
                            Text("See translation")
                                .foregroundColor(.gray)
                        }
                        
                        Spacer()
                    }
                    .padding()
                    
                    // Bottom Navigation
                    HStack {
                        BottomNavButton(imageName: "house", text: "Home")
                        BottomNavButton(imageName: "person.2.fill", text: "Friends", notificationCount: 1)
                        AddButton()
                        BottomNavButton(imageName: "envelope", text: "Inbox")
                        BottomNavButton(imageName: "person.circle", text: "Profile")
                    }
                    .frame(height: 50)
                    .background(Color.black.opacity(0.6))
                    .foregroundColor(.white)
                }
            }
        }
    }
}

struct ProfileButton: View {
    var body: some View {
        Button(action: {
            // Profile button action
        }) {
            Image("profileImage") // Replace with your profile image
                .resizable()
                .frame(width: 50, height: 50)
                .clipShape(Circle())
                .overlay(Circle().stroke(Color.white, lineWidth: 2))
                .background(Circle().fill(Color.red).frame(width: 18, height: 18).offset(x: 20, y: 20))
        }
    }
}

struct ActionButton: View {
    let imageName: String
    let count: String
    
    var body: some View {
        VStack {
            Image(systemName: imageName)
                .font(.title)
                .foregroundColor(.white)
            Text(count)
                .foregroundColor(.white)
                .font(.footnote)
        }
    }
}

struct BottomNavButton: View {
    let imageName: String
    let text: String
    var notificationCount: Int? = nil
    
    var body: some View {
        VStack {
            Image(systemName: imageName)
                .font(.title2)
            Text(text)
                .font(.footnote)
                .foregroundColor(.white)
            
            if let count = notificationCount {
                Text("\(count)")
                    .padding(4)
                    .background(Color.red)
                    .clipShape(Circle())
                    .foregroundColor(.white)
                    .font(.footnote)
                    .offset(x: 14, y: -24)
            }
        }
    }
}

struct AddButton: View {
    var body: some View {
        ZStack {
            Circle()
                .fill(Color.white)
                .frame(width: 40, height: 40)
            Image(systemName: "plus.circle.fill")
                .foregroundColor(.blue)
                .font(.title)
        }
        .offset(y: -10)
    }
}

struct TikTokCameraInterfaceView_Previews: PreviewProvider {
    static var previews: some View {
        TikTokCameraInterfaceView()
    }
}
